(deftheme dark
  "My dark theme.")

(custom-theme-set-faces
 'dark
 '(default ((((class color) (min-colors 89)) (:foreground "#d3d3d3" :background "#000000" :family "Iosevka" :slant normal :weight normal :height 98 :width normal))))
 '(company-preview ((t (:background "#292500"))))
 '(company-tooltip ((t (:background "#2B2A00"))))
 '(company-tooltip-selection ((t (:background "#1F1F00"))))
 '(diff-hl-change ((t (:background "#FFA060" :foreground "#000000"))))
 '(diff-hl-dired-unknown ((t (:inherit dired-ignored :background "#3CD681" :foreground "#000000"))))
 '(dired-rainbow-directory-face ((t (:foreground "#EB6C88" :weight bold))))
 '(ensime-implicit-highlight ((t (:underline "dim gray"))))
 '(eyebrowse-mode-line-active ((t (:inherit mode-line-emphasis :underline t))))
 '(fixed-pitch ((t (:height 0.84 :family "Iosevka"))))
 '(flymake-error ((t (:foreground "#8b0000" :box (:line-width 1 :color "#450000" :style released-button) :underline (:color "#5F0000" :style wave) :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#888888" :slant italic))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#96CBFE"))))
 '(font-lock-doc-face ((t (:inherit font-lock-string-face :foreground "#FFF150"))))
 '(font-lock-string-face ((t (:foreground "#e67128" :slant italic))))
 '(font-lock-variable-name-face ((t (:foreground "#EBEB81"))))
 '(font-lock-type-face ((t (:foreground "#75EE7B"))))

 `(font-lock-keyword-face ((t (:foreground "#ffad29" :weight bold))))
;; `(font-lock-type-face ((t (:foreground "#34cae2"))))
 `(font-lock-builtin-face ((t (:foreground "#23d7d7"))))
 `(font-lock-function-name-face ((t (:foreground "#00ede1" :weight bold))))

 `(button ((t (:underline t))))
 `(link ((t (:foreground "#59e9ff" :underline t))))
 `(link-visited ((t (:foreground "#ed74cd" :underline t))))

 `(message-header-name ((t (:foreground "#ffad29" :weight bold))))
 `(message-header-cc ((t (:foreground "#e67128"))))
 `(message-header-other ((t (:foreground "#e67128"))))
 `(message-header-subject ((t (:foreground "#dbdb95"))))
 `(message-header-to ((t (:foreground "#00ede1"))))
 `(message-cited-text ((t (:foreground "#74af68"))))
 `(message-separator ((t (:foreground "#23d7d7"))))

 '(fringe ((t (:background "#000000"))))
 '(git-gutter:modified ((t (:inherit default :foreground "#629CE4" :weight bold))))
 '(highlight ((t (:background "#724F07"))))
 '(highlight-indent-guides-character-face ((t (:foreground "#3F3F3F"))))
 '(highlight-indent-guides-stack-character-face ((t (:foreground "#3F3F3F"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#9D9A71"))))
 '(hl-line ((t (:background "#3d3708"))))
 '(hs-ellipsis ((t (:background "#00215D" :box (:line-width 1 :color "#6A85ED" :style pressed-button)))))
 '(italic ((t (:slant italic))))
 '(kubernetes-progress-indicator ((t (:foreground "#40E974"))))
 '(logview-information-entry ((t (:background "#022502"))))
 '(logview-timestamp ((t (:inherit font-lock-builtin-face :overline t :underline nil))))
 '(logview-warning-entry ((t (:background "#221900"))))
 '(lsp-ui-doc-header ((t (:background "#5D5FB1" :foreground "black"))))
 '(lsp-ui-sideline-code-action ((t (:foreground "#808346"))))
 '(lsp-ui-sideline-global ((t (:foreground "burlywood"))))
 '(magit-mode-line-process ((t (:foreground "#74E815" :weight bold))))
 '(magit-section-highlight ((t (:background "#1c1c1c"))))
 '(markdown-bold-face ((t (:inherit bold :foreground "#ffffff"))))
 '(markdown-code-face ((t (:inherit (fixed-pitch font-lock-constant-face) :background "#1b2129"))))
 '(markdown-header-face-1 ((t (:inherit outline-1 :overline t))))
 '(markdown-header-face-2 ((t (:inherit outline-2 :overline t))))
 '(markdown-header-face-3 ((t (:inherit outline-3 :overline t))))
 '(markdown-header-face-4 ((t (:inherit outline-4))))
 '(markdown-header-face-5 ((t (:inherit outline-5))))
 '(markdown-pre-face ((t (:background "#1b2129"))))
 '(mode-line ((t (:background "#333333" :foreground "gold3" :box (:line-width -1 :color "gold4")))))
 '(mode-line-inactive ((t (:background "black" :foreground "dark gray" :box (:line-width -1 :color "LightSteelBlue4")))))
 '(mu4e-header-highlight-face ((t (:inherit region :underline t :weight bold))))
 '(mu4e-unread-face ((t (:inherit font-lock-keyword-face :weight bold))))
 '(org-block ((t (:inherit (shadow fixed-pitch) :background "#1b2129"))))
 '(org-code ((t (:inherit org-block))))
 '(org-date ((t (:inherit fixed-pitch :background "black" :foreground "Cyan" :box (:line-width 1 :color "#00455D") :underline nil))))
 '(org-done ((t (:foreground "#005617" :weight bold))))
 '(org-formula ((t (:inherit fixed-pitch :foreground "#73331A"))))
 '(org-level-1 ((t (:inherit org-tree-slide-heading-level-1-init))))
 '(org-level-2 ((t (:inherit org-tree-slide-heading-level-2-init))))
 '(org-level-3 ((t (:inherit org-tree-slide-heading-level-3-init))))
 '(org-level-4 ((t (:inherit org-tree-slide-heading-level-4-init))))
 '(org-meta-line ((t (:inherit font-lock-comment-face :foreground "#8A8460" :height 0.8))))
 '(org-superstar-item ((t (:inherit default :box (:line-width 4 :color "#000")))))
 '(org-table ((t (:inherit fixed-pitch :foreground "LightSkyBlue"))))
 '(org-todo ((t (:foreground "#DD3794" :weight bold))))
 '(org-tree-slide-header-overlay-face ((t (:background "#000000" :foreground "#d3d3d3" :weight bold :height 1.3))))
 '(org-tree-slide-heading-level-1 ((t (:inherit outline-1))))
 '(org-tree-slide-heading-level-2 ((t (:inherit outline-2))))
 '(org-verbatim ((t (:inherit markdown-code-face))))
 '(outline-1 ((t (:foreground "#A6EDEA" :weight bold :height 1.5))))
 '(outline-2 ((t (:foreground "#EEFFB3" :weight bold :height 1.4))))
 '(outline-3 ((t (:foreground "#A7E2A7" :weight bold :height 1.0))))
 '(outline-4 ((t (:foreground "#D987D8" :weight bold :height 1.0))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#FF5555"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#02B692"))))
 '(rainbow-delimiters-depth-3-face ((t (:inherit rainbow-delimiters-base-face :foreground "#F0BA6D"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#00FFC7"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#79C8E1"))))
 '(rainbow-delimiters-depth-7-face ((t (:inherit rainbow-delimiters-base-face :foreground "#DE56C5"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#998EDB"))))
 '(rainbow-delimiters-unmatched-face ((t (:inherit rainbow-delimiters-base-face :background "#88090B"))))
 '(region ((t (:background "#5b3636"))))
 '(shadow ((t (:foreground "grey70"))))
 '(show-paren-match ((t (:background "#4C7E28"))))
 '(term-color-red ((t (:background "#8c5353" :foreground "#FF0000"))))
 '(variable-pitch ((t (:height 1.3 :family "ETBembo"))))
 '(whitespace-indentation ((t (:foreground "firebrick"))))
 '(whitespace-line ((t (:background "#40002A"))))
 '(whitespace-space ((t (:foreground "#66CACC"))))
 '(whitespace-trailing ((t (:background "dark red")))))

(provide-theme 'dark)
