;;; telega-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from telega.el

(defvar telega-prefix-map (let ((map (make-sparse-keymap))) (define-key map (kbd "a") 'telega-account-switch) (define-key map (kbd "b") 'telega-switch-buffer) (define-key map (kbd "c") 'telega-chat-with) (define-key map (kbd "e") 'telega-edit-file-switch-buffer) (define-key map (kbd "i") 'telega-switch-important-chat) (define-key map (kbd "f") 'telega-buffer-file-send) (define-key map (kbd "s") 'telega-saved-messages) (define-key map (kbd "t") 'telega) (define-key map (kbd "u") 'telega-switch-unread-chat) (define-key map (kbd "w") 'telega-browse-url) map) "\
Keymap for the telega commands.")
(autoload 'telega "telega" "\
Start telega.el Telegram client.
Pop to root buffer.
If `\\[universal-argument]' is specified, then do not pop to root buffer.

(fn &optional ARG)" t)
(autoload 'telega-kill "telega" "\
Kill currently running telega.
With prefix arg FORCE quit without confirmation.

(fn FORCE)" t)
(autoload 'telega-version "telega" "\
Return telega (and TDLib) version.
If `\\[universal-argument]' is specified, then insert the version
string at point.

(fn &optional INSERT-P)" t)
(autoload 'telega-report-bug "telega" "\
Create bug report for https://github.com/zevlg/telega.el/issues." t)
(register-definition-prefixes "telega" '("telega-"))


;;; Generated autoloads from telega-chat.el

(autoload 'telega-chatbuf-input-as-region-advice "telega-chat" "\
Advice for commands accepting region.
If point is inside telega chatbuf input, then call region command
with input prompt as region.

(fn ORIG-REGION-FUNC START END &rest ARGS)")
(register-definition-prefixes "telega-chat" '("telega-" "with-telega-chatbuf-action"))


;;; Generated autoloads from telega-company.el

(autoload 'telega-company-emoji "telega-company" "\
Backend for `company' to complete emojis.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(autoload 'telega-company-telegram-emoji "telega-company" "\
Backend for `company' to complete emojis using `searchEmojis' TDLib method.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(autoload 'telega-company-username "telega-company" "\
Backend for `company' to complete usernames.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(autoload 'telega-company-hashtag "telega-company" "\
Backend for `company' to complete recent hashtags.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(autoload 'telega-company-botcmd "telega-company" "\


(fn COMMAND &optional ARG &rest IGNORED)" t)
(autoload 'telega-company-markdown-precode "telega-company" "\


(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "telega-company" '("telega-company-"))


;;; Generated autoloads from telega-core.el

(register-definition-prefixes "telega-core" '("lambda-with-current-buffer" "telega-" "with-telega-"))


;;; Generated autoloads from telega-customize.el

(register-definition-prefixes "telega-customize" '("telega-"))


;;; Generated autoloads from telega-emoji.el

(register-definition-prefixes "telega-emoji" '("telega-"))


;;; Generated autoloads from telega-ffplay.el

(register-definition-prefixes "telega-ffplay" '("telega-"))


;;; Generated autoloads from telega-filter.el

(register-definition-prefixes "telega-filter" '("telega-" "tracking-buffers"))


;;; Generated autoloads from telega-folders.el

(register-definition-prefixes "telega-folders" '("telega-"))


;;; Generated autoloads from telega-i18n.el

(register-definition-prefixes "telega-i18n" '("telega-i18n"))


;;; Generated autoloads from telega-info.el

(register-definition-prefixes "telega-info" '("telega-"))


;;; Generated autoloads from telega-inline.el

(register-definition-prefixes "telega-inline" '("telega-"))


;;; Generated autoloads from telega-ins.el

(register-definition-prefixes "telega-ins" '("telega-"))


;;; Generated autoloads from telega-match.el

(register-definition-prefixes "telega-match" '("chat" "define-telega-matcher" "msg" "nil" "sender" "story" "telega-" "topic" "user"))


;;; Generated autoloads from telega-media.el

(register-definition-prefixes "telega-media" '("telega-"))


;;; Generated autoloads from telega-modes.el

(defvar telega-mode-line-mode nil "\
Non-nil if Telega-Mode-Line mode is enabled.
See the `telega-mode-line-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `telega-mode-line-mode'.")
(custom-autoload 'telega-mode-line-mode "telega-modes" nil)
(autoload 'telega-mode-line-mode "telega-modes" "\
Toggle display of the unread chats/mentions in the modeline.

This is a global minor mode.  If called interactively, toggle the
`Telega-Mode-Line mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='telega-mode-line-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(defvar telega-appindicator-mode nil "\
Non-nil if Telega-Appindicator mode is enabled.
See the `telega-appindicator-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `telega-appindicator-mode'.")
(custom-autoload 'telega-appindicator-mode "telega-modes" nil)
(autoload 'telega-appindicator-mode "telega-modes" "\
Toggle display of the unread chats/mentions in the system tray.

This is a global minor mode.  If called interactively, toggle the
`Telega-Appindicator mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='telega-appindicator-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(defvar telega-autoplay-mode nil "\
Non-nil if Telega-Autoplay mode is enabled.
See the `telega-autoplay-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `telega-autoplay-mode'.")
(custom-autoload 'telega-autoplay-mode "telega-modes" nil)
(autoload 'telega-autoplay-mode "telega-modes" "\
Automatically play animation messages.

This is a global minor mode.  If called interactively, toggle the
`Telega-Autoplay mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='telega-autoplay-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'telega-squash-message-mode "telega-modes" "\
Toggle message squashing minor mode.

This is a minor mode.  If called interactively, toggle the
`Telega-Squash-Message mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `telega-squash-message-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(defvar global-telega-squash-message-mode nil "\
Non-nil if Global Telega-Squash-Message mode is enabled.
See the `global-telega-squash-message-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-telega-squash-message-mode'.")
(custom-autoload 'global-telega-squash-message-mode "telega-modes" nil)
(autoload 'global-telega-squash-message-mode "telega-modes" "\
Global mode to squashing messages.

This is a global minor mode.  If called interactively, toggle the
`Global Telega-Squash-Message mode' mode.  If the prefix argument
is positive, enable the mode, and if it is zero or negative,
disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='global-telega-squash-message-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'telega-edit-file-mode "telega-modes" "\
Minor mode to edit files from Telegram messages.

Can be enabled only for content from editable messages.

This is a minor mode.  If called interactively, toggle the
`Telega-Edit-File mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `telega-edit-file-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(defvar telega-recognize-voice-message-mode nil "\
Non-nil if Telega-Recognize-Voice-Message mode is enabled.
See the `telega-recognize-voice-message-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `telega-recognize-voice-message-mode'.")
(custom-autoload 'telega-recognize-voice-message-mode "telega-modes" nil)
(autoload 'telega-recognize-voice-message-mode "telega-modes" "\
Global mode to automatically recognize speech in the voice messages.

This is a global minor mode.  If called interactively, toggle the
`Telega-Recognize-Voice-Message mode' mode.  If the prefix
argument is positive, enable the mode, and if it is zero or
negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value
\\='telega-recognize-voice-message-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(defvar telega-auto-download-mode nil "\
Non-nil if Telega-Auto-Download mode is enabled.
See the `telega-auto-download-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `telega-auto-download-mode'.")
(custom-autoload 'telega-auto-download-mode "telega-modes" nil)
(autoload 'telega-auto-download-mode "telega-modes" "\
Global mode to automatically download media files.

This is a global minor mode.  If called interactively, toggle the
`Telega-Auto-Download mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='telega-auto-download-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "telega-modes" '("telega-"))


;;; Generated autoloads from telega-msg.el

(register-definition-prefixes "telega-msg" '("telega-"))


;;; Generated autoloads from telega-notifications.el

(defvar telega-notifications-mode nil "\
Non-nil if Telega-Notifications mode is enabled.
See the `telega-notifications-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `telega-notifications-mode'.")
(custom-autoload 'telega-notifications-mode "telega-notifications" nil)
(autoload 'telega-notifications-mode "telega-notifications" "\
Telega D-Bus notifications.

This is a global minor mode.  If called interactively, toggle the
`Telega-Notifications mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='telega-notifications-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "telega-notifications" '("telega-"))


;;; Generated autoloads from telega-obsolete.el

(register-definition-prefixes "telega-obsolete" '("telega-obsolete--"))


;;; Generated autoloads from telega-root.el

(register-definition-prefixes "telega-root" '("telega-" "with-telega-root-view-ewoc"))


;;; Generated autoloads from telega-server.el

(autoload 'telega-server-build "telega-server" "\
Build and install `telega-server' binary.
If BUILD-FLAGS is specified, then rebuild server without any
queries using this flags for building, could be empty string.
Otherwise query user about building flags.

(fn &optional BUILD-FLAGS)" t)
(register-definition-prefixes "telega-server" '("telega-" "with-telega-deferred-events"))


;;; Generated autoloads from telega-sort.el

(register-definition-prefixes "telega-sort" '("chat" "define-telega-sorter" "join-date" "last-seen" "member-count" "nearby-distance" "online-members" "order" "telega-" "title" "unread-count"))


;;; Generated autoloads from telega-sticker.el

(register-definition-prefixes "telega-sticker" '("telega-"))


;;; Generated autoloads from telega-story.el

(register-definition-prefixes "telega-story" '("telega-"))


;;; Generated autoloads from telega-tdlib.el

(register-definition-prefixes "telega-tdlib" '("teleg" "with-telega-server-reply"))


;;; Generated autoloads from telega-tdlib-events.el

(register-definition-prefixes "telega-tdlib-events" '("telega-" "tracking-buffers" "with-telega--msg-update-event"))


;;; Generated autoloads from telega-tme.el

(register-definition-prefixes "telega-tme" '("telega-tme-"))


;;; Generated autoloads from telega-topic.el

(register-definition-prefixes "telega-topic" '("telega-"))


;;; Generated autoloads from telega-user.el

(register-definition-prefixes "telega-user" '("telega-"))


;;; Generated autoloads from telega-util.el

(register-definition-prefixes "telega-util" '("telega-" "with-telega-symbol-animate"))


;;; Generated autoloads from telega-voip.el

(register-definition-prefixes "telega-voip" '("telega-"))


;;; Generated autoloads from telega-vvnote.el

(register-definition-prefixes "telega-vvnote" '("telega-"))


;;; Generated autoloads from telega-webpage.el

(register-definition-prefixes "telega-webpage" '("telega-"))

;;; End of scraped data

(provide 'telega-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; telega-autoloads.el ends here
