;;; daemons-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from daemons.el

(autoload 'daemons-status "daemons" "\
Show the status of the daemon NAME.

(fn NAME)" t)
(autoload 'daemons-start "daemons" "\
Start the daemon NAME.  Show results in an output buffer.

(fn NAME)" t)
(autoload 'daemons-stop "daemons" "\
Stop the daemon NAME.  Show results in an output buffer.

(fn NAME)" t)
(autoload 'daemons-restart "daemons" "\
Restart the daemon NAME.  Show results in an ouptut buffer.

(fn NAME)" t)
(autoload 'daemons-reload "daemons" "\
Reload the daemon NAME.  Show results in an output buffer.

(fn NAME)" t)
(autoload 'daemons-enable "daemons" "\
Enable the daemon NAME.  Show results in an output buffer.

(fn NAME)" t)
(autoload 'daemons-disable "daemons" "\
Disable the daemon NAME.  Show results in an output buffer.

(fn NAME)" t)
(autoload 'daemons "daemons" "\
Open the list of system daemons (services) for user management.

This opens a ‘daemons-mode’ list buffer.  Move the cursor to a daemon line and
execute one of the commands in `describe-mode' to show status and manage the
state of the daemon." t)
(register-definition-prefixes "daemons" '("daemons-"))


;;; Generated autoloads from daemons-brew.el

(register-definition-prefixes "daemons-brew" '("daemons-brew--"))


;;; Generated autoloads from daemons-openrc.el

(register-definition-prefixes "daemons-openrc" '("daemons-openrc--"))


;;; Generated autoloads from daemons-shepherd.el

(register-definition-prefixes "daemons-shepherd" '("daemons-shepherd--"))


;;; Generated autoloads from daemons-systemd.el

(register-definition-prefixes "daemons-systemd" '("daemons-"))


;;; Generated autoloads from daemons-sysvinit.el

(register-definition-prefixes "daemons-sysvinit" '("daemons-sysvinit--"))

;;; End of scraped data

(provide 'daemons-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; daemons-autoloads.el ends here
