;;; org-caldav-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-caldav.el

(autoload 'org-caldav-sync "org-caldav" "\
Sync Org with calendar." t)
(autoload 'org-caldav-import-ics-buffer-to-org "org-caldav" "\
Add ics content in current buffer to `org-caldav-inbox'.")
(autoload 'org-caldav-import-ics-to-org "org-caldav" "\
Add ics content in PATH to `org-caldav-inbox'.

(fn PATH)")
(register-definition-prefixes "org-caldav" '("org-caldav-"))

;;; End of scraped data

(provide 'org-caldav-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-caldav-autoloads.el ends here
