;;; flyspell-popup-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flyspell-popup.el

(autoload 'flyspell-popup-correct "flyspell-popup" "\
Use popup for flyspell correction.
Adapted from `flyspell-correct-word-before-point'." t)
(autoload 'flyspell-popup-auto-correct-mode "flyspell-popup" "\
Minor mode for automatically correcting word at point.

This is a minor mode.  If called interactively, toggle the
`Flyspell-Popup-Auto-Correct mode' mode.  If the prefix argument
is positive, enable the mode, and if it is zero or negative,
disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `flyspell-popup-auto-correct-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "flyspell-popup" '("flyspell-popup-"))

;;; End of scraped data

(provide 'flyspell-popup-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flyspell-popup-autoloads.el ends here
