;;; noccur-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from noccur.el

(autoload 'noccur-dired "noccur" "\
Perform `multi-occur' with REGEXP in all dired marked files.
When called with a prefix argument NLINES, display NLINES lines before and after.

(fn REGEXP &optional NLINES)" t)
(autoload 'noccur-project "noccur" "\
Perform `multi-occur' with REGEXP in the current project files.
When called with a prefix argument NLINES, display NLINES lines before and after.
If DIRECTORY-TO-SEARCH is specified, this directory will be searched recursively;
otherwise, the user will be prompted to specify a directory to search.

For performance reasons, files are filtered using 'find' or 'git
ls-files' and 'grep'.

(fn REGEXP &optional NLINES DIRECTORY-TO-SEARCH)" t)
(register-definition-prefixes "noccur" '("noccur--"))

;;; End of scraped data

(provide 'noccur-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; noccur-autoloads.el ends here
