;;; ob-http-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ob-http.el

(register-definition-prefixes "ob-http" '("ob-http" "org-babel-"))


;;; Generated autoloads from ob-http-mode.el

(register-definition-prefixes "ob-http-mode" '("ob-http-mode"))

;;; End of scraped data

(provide 'ob-http-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ob-http-autoloads.el ends here
