;;; company-emoji-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-emoji.el

(autoload 'company-emoji "company-emoji" "\
Provide a backend for company to complete emoji-words.

company.el calls this function, and passes a COMMAND to it that
depends on the context: 'prefix', 'candidates', 'annotation',
etc.  In some contexts it also passes ARG, which is the list of
candidates that match what has been typed so far.  Sometimes ARG
is a single candidate, as when COMMAND is 'annotation' or
'post-completion'.  Other arguments are IGNORED.

(fn COMMAND &optional ARG &rest IGNORED)")
(autoload 'company-emoji-init "company-emoji" "\
Add emoji to the company backends." t)
(register-definition-prefixes "company-emoji" '("company-emoji"))


;;; Generated autoloads from company-emoji-list.el

(register-definition-prefixes "company-emoji-list" '("company-emoji-list-create"))

;;; End of scraped data

(provide 'company-emoji-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-emoji-autoloads.el ends here
